/*
  PC Scan Code to Dragon Column/Row translation table.

  Encoded as follows, 
  Each record consists of 3 bytes :-
 
  1) The prefix code, either SCAN_CODE_NO_PREFIX, or SCAN_CODE_ESCAPE
  2) The PC scan code to check for, from scancode.h
  3) The target machine key it represents, from constant table (scancode.h).

  This table should ONLY contain mappings for which there is a valid
  output key.

  Working out this table took far too long !!!!
*/

#include "scancode.h"
#include "io.h"
#include "status.h"

const uint8_t ScancodeTableDragonBeta[] PROGMEM = {
// Prefix code			Scancode				Keycode
SCAN_CODE_NO_PREFIX,	SCAN_CODE_A,			BETA_KEY_A,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_B,			BETA_KEY_B,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_C,			BETA_KEY_C,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_D,			BETA_KEY_D,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_E,			BETA_KEY_E,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F,			BETA_KEY_F,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_G,			BETA_KEY_G,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_H,			BETA_KEY_H,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_I,			BETA_KEY_I,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_J,			BETA_KEY_J,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_K,			BETA_KEY_K,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_L,			BETA_KEY_L,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_M,			BETA_KEY_M,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_N,			BETA_KEY_N,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_O,			BETA_KEY_O,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_P,			BETA_KEY_P,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Q,			BETA_KEY_Q,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_R,			BETA_KEY_R,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_S,			BETA_KEY_S,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_T,			BETA_KEY_T,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_U,			BETA_KEY_U,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_V,			BETA_KEY_V,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_W,			BETA_KEY_W,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_X,			BETA_KEY_X,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Y,			BETA_KEY_Y,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Z,			BETA_KEY_Z,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_0,			BETA_KEY_0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_1,			BETA_KEY_1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_2,			BETA_KEY_2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_3,			BETA_KEY_3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_4,			BETA_KEY_4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_5,			BETA_KEY_5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_6,			BETA_KEY_6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_7,			BETA_KEY_7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_8,			BETA_KEY_8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_9,			BETA_KEY_9,

// Keypad
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP0,			BETA_KEY_KP0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP1,			BETA_KEY_KP1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP2,			BETA_KEY_KP2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP3,			BETA_KEY_KP3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP4,			BETA_KEY_KP4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP5,			BETA_KEY_KP5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP6,			BETA_KEY_KP6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP7,			BETA_KEY_KP7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP8,			BETA_KEY_KP8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP9,			BETA_KEY_KP9,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPSTAR,		BETA_KEY_KPSTAR,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPMINUS,		BETA_KEY_KPHASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPPOINT,		BETA_KEY_KPPOINT,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_SPACE,		BETA_KEY_SPACE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_POINT,		BETA_KEY_POINT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_COMMA,		BETA_KEY_COMMA,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SLASH,		BETA_KEY_SLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SEMICOLON,	BETA_KEY_SEMICOLON,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSQBRACK,		BETA_KEY_RSQBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSQBRACK,		BETA_KEY_LSQBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_QUOTE,		BETA_KEY_AT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BSLASH,		BETA_KEY_BSLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_MINUS,		BETA_KEY_MINUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_EQUAL,		BETA_KEY_COLON,
//SCAN_CODE_NO_PREFIX,	SCAN_CODE_TILDE,		BETA_KEY_CLARET,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_BACKSPACE,	BETA_KEY_DELETE,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSHIFT,		BETA_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LALT,			BETA_KEY_FUNC,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSHIFT,		BETA_KEY_SHIFT,
SCAN_CODE_ESCAPE,		SCAN_CODE_LGUI,			BETA_KEY_SHIFT,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_LCTRL,		BETA_KEY_CTRL,
SCAN_CODE_ESCAPE,		SCAN_CODE_RCTRL,		BETA_KEY_CTRL,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ENTER,		BETA_KEY_ENTER,
SCAN_CODE_ESCAPE,		SCAN_CODE_KPENTER,		BETA_KEY_ENTER,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ESC,			BETA_KEY_BREAK,
SCAN_CODE_ESCAPE,		SCAN_CODE_PAUSE,		BETA_KEY_BREAK,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_CAPSLOCK,		BETA_KEY_CAPS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_TAB,			BETA_KEY_TAB,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_INSERT,		BETA_KEY_CLEAR,

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};


/*
  The shift key table, this has the same format as the above standard 
  key table, however when one of these keys is pressed, the output shift 
  key will also be pressed before the key, and released after the key.
	
  This allows as single PC key to translate to a SHIFT-KEY combination 
  on the output matrix. 
  
  A similar method could be used for other modifier keys.
*/

const uint8_t ScancodeShiftTableDragonBeta[] PROGMEM = {
// Prefix code			Scancode				Keycode

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};


void ScancodeInit(matrix_t *ToInit)
{
	log0("ScancodeInit()\n");

	ToInit->ScancodeTable=(ptable_t)&ScancodeTableDragonBeta;
	ToInit->ScancodeShiftTable=(ptable_t)&ScancodeShiftTableDragonBeta;
	ToInit->matrix_shift=BETA_KEY_SHIFT;
	
	ToInit->matrix_reset=RESET_KEY;
}