/*
  PC Scan Code to Apple IIc Column/Row translation table.
   
  Encoded as follows, 
  Each record consists of 3 bytes :-
 
  1) The prefix code, either SCAN_CODE_NO_PREFIX, or SCAN_CODE_ESCAPE
  2) The PC scan code to check for, from scancode.h
  3) The target key it represents, from constant table above.

  This table should ONLY contain mappings for which there is a valid
  output key.

  Working out this table took far too long !!!!
*/

#include "scancode.h"
#include "globalio.h"
#include "io.h"
#include "status.h"

const uint8_t ScancodeTableCPC[] PROGMEM = {
// Prefix code		Scancode			Keycode
SCAN_CODE_NO_PREFIX,	SCAN_CODE_A,			AIIC_KEY_A,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_B,			AIIC_KEY_B,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_C,			AIIC_KEY_C,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_D,			AIIC_KEY_D,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_E,			AIIC_KEY_E,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F,			AIIC_KEY_F,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_G,			AIIC_KEY_G,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_H,			AIIC_KEY_H,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_I,			AIIC_KEY_I,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_J,			AIIC_KEY_J,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_K,			AIIC_KEY_K,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_L,			AIIC_KEY_L,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_M,			AIIC_KEY_M,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_N,			AIIC_KEY_N,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_O,			AIIC_KEY_O,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_P,			AIIC_KEY_P,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Q,			AIIC_KEY_Q,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_R,			AIIC_KEY_R,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_S,			AIIC_KEY_S,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_T,			AIIC_KEY_T,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_U,			AIIC_KEY_U,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_V,			AIIC_KEY_V,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_W,			AIIC_KEY_W,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_X,			AIIC_KEY_X,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Y,			AIIC_KEY_Y,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Z,			AIIC_KEY_Z,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_0,			AIIC_KEY_0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_1,			AIIC_KEY_1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_2,			AIIC_KEY_2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_3,			AIIC_KEY_3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_4,			AIIC_KEY_4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_5,			AIIC_KEY_5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_6,			AIIC_KEY_6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_7,			AIIC_KEY_7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_8,			AIIC_KEY_8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_9,			AIIC_KEY_9,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ENTER,		AIIC_KEY_ENTER,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SPACE,		AIIC_KEY_SPACE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSHIFT,		AIIC_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSHIFT,		AIIC_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LCTRL,		AIIC_KEY_CTRL,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ESC,	                AIIC_KEY_ESC,
SCAN_CODE_ESCAPE,	SCAN_CODE_LARROW,		AIIC_KEY_LEFT,
SCAN_CODE_ESCAPE,	SCAN_CODE_RARROW,		AIIC_KEY_RIGHT,
SCAN_CODE_ESCAPE,	SCAN_CODE_UARROW,		AIIC_KEY_UP,
SCAN_CODE_ESCAPE,	SCAN_CODE_DARROW,		AIIC_KEY_DOWN,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BACKSPACE,	        AIIC_KEY_DEL,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSQBRACK,		AIIC_KEY_LSQBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSQBRACK,		AIIC_KEY_RSQBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_TILDE,		AIIC_KEY_TILDE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SEMICOLON,	        AIIC_KEY_SEMICOLON,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_QUOTE,	        AIIC_KEY_DQUOTE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_COMMA,	        AIIC_KEY_LT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_POINT,	        AIIC_KEY_GT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SLASH,	        AIIC_KEY_QUESTION,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BSLASH,	        AIIC_KEY_TILDE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_UK102_BS,	        AIIC_KEY_BSLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_MINUS,	        AIIC_KEY_MINUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_EQUAL,	        AIIC_KEY_EQUAL,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_TAB,	                AIIC_KEY_TAB,

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};


/*
  The shift key table, this has the same format as the above standard 
  key table, however when one of these keys is pressed, the output shift 
  key will also be pressed before the key, and released after the key.
	
  This allows as single PC key to translate to a SHIFT-KEY combination 
  on the output matrix. 
  
  A similar method could be used for other modifier keys.
*/

const uint8_t ScancodeShiftTableCPC[] PROGMEM = {
// Prefix code			Scancode				Keycode

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};




void ScancodeInit(matrix_t *ToInit)
{
  logv0("Amstrad CPC-6128 machine driver selected\n");
  ToInit->ScancodeTable=(uint8_t *)ScancodeTableCPC;
  ToInit->ScancodeShiftTable=(uint8_t *)ScancodeShiftTableCPC;
  ToInit->matrix_shift=AIIC_KEY_SHIFT;
  
  ToInit->callback=&TargetKeyCallback;
  ToInit->matrix_reset=RESET_KEY;
}
