/*
  PC Scan Code to Acorn BBC A/B/B+ Column/Row translation table.
  
  Note the BBC A/B/B+ will need extra hardware beyond the matrix output,
  this is to replicate the circuit surrounding the matrix on a real BBC
  keyboard.
  
  Encoded as follows, 
  Each record consists of 3 bytes :-
 
  1) The prefix code, either SCAN_CODE_NO_PREFIX, or SCAN_CODE_ESCAPE
  2) The PC scan code to check for, from scancode.h
  3) The target key it represents, from constant table above.

  This table should ONLY contain mappings for which there is a valid
  output key.

  Working out this table took far too long !!!!
*/

#include "scancode.h"

const uint8_t ScancodeTableBBCMaster[] PROGMEM = {
// Prefix code			Scancode				Keycode
SCAN_CODE_NO_PREFIX,	SCAN_CODE_A,			BBCM_KEY_A,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_B,			BBCM_KEY_B,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_C,			BBCM_KEY_C,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_D,			BBCM_KEY_D,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_E,			BBCM_KEY_E,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F,			BBCM_KEY_F,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_G,			BBCM_KEY_G,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_H,			BBCM_KEY_H,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_I,			BBCM_KEY_I,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_J,			BBCM_KEY_J,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_K,			BBCM_KEY_K,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_L,			BBCM_KEY_L,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_M,			BBCM_KEY_M,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_N,			BBCM_KEY_N,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_O,			BBCM_KEY_O,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_P,			BBCM_KEY_P,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Q,			BBCM_KEY_Q,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_R,			BBCM_KEY_R,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_S,			BBCM_KEY_S,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_T,			BBCM_KEY_T,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_U,			BBCM_KEY_U,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_V,			BBCM_KEY_V,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_W,			BBCM_KEY_W,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_X,			BBCM_KEY_X,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Y,			BBCM_KEY_Y,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Z,			BBCM_KEY_Z,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_0,			BBCM_KEY_0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_1,			BBCM_KEY_1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_2,			BBCM_KEY_2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_3,			BBCM_KEY_3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_4,			BBCM_KEY_4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_5,			BBCM_KEY_5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_6,			BBCM_KEY_6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_7,			BBCM_KEY_7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_8,			BBCM_KEY_8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_9,			BBCM_KEY_9,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_ENTER,		BBCM_KEY_ENTER,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SPACE,		BBCM_KEY_SPACE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSHIFT,		BBCM_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSHIFT,		BBCM_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LCTRL,		BBCM_KEY_CTRL,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_F1,			BBCM_KEY_F0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F1,			BBCM_KEY_F1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F2,			BBCM_KEY_F2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F3,			BBCM_KEY_F3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F4,			BBCM_KEY_F4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F5,			BBCM_KEY_F5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F6,			BBCM_KEY_F6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F7,			BBCM_KEY_F7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F8,			BBCM_KEY_F8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F9,			BBCM_KEY_F9,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_TAB,			BBCM_KEY_TAB,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_TILDE,		BBCM_KEY_AT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LALT,			BBCM_KEY_SHIFTLK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_ESC,			BBCM_KEY_ESC,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_COMMA,		BBCM_KEY_COMMA,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_POINT,		BBCM_KEY_PERIOD,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SLASH,		BBCM_KEY_SLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SEMICOLON,	BBCM_KEY_SEMI,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_MINUS,		BBCM_KEY_MINUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_QUOTE,		BBCM_KEY_COLON,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSQBRACK,		BBCM_KEY_LEFTSB,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSQBRACK,		BBCM_KEY_RIGHTSB,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_EQUAL,		BBCM_KEY_CLARET,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_CAPSLOCK,		BBCM_KEY_CAPS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BSLASH,		BBCM_KEY_UNDER,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_UK102_BS,		BBCM_KEY_PIPE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BACKSPACE,	BBCM_KEY_DEL,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_ESC,			BBCM_KEY_ESC,

SCAN_CODE_ESCAPE,		SCAN_CODE_RALT,			BBCM_KEY_COPY,
SCAN_CODE_ESCAPE,		SCAN_CODE_RCTRL,		BBCM_KEY_CTRL,
SCAN_CODE_ESCAPE,		SCAN_CODE_END,			BBCM_KEY_COPY,
SCAN_CODE_ESCAPE,		SCAN_CODE_LARROW,		BBCM_KEY_LEFT,
SCAN_CODE_ESCAPE,		SCAN_CODE_RARROW,		BBCM_KEY_RIGHT,
SCAN_CODE_ESCAPE,		SCAN_CODE_UARROW,		BBCM_KEY_UP,
SCAN_CODE_ESCAPE,		SCAN_CODE_DARROW,		BBCM_KEY_DOWN,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP0,			BBCM_KEY_KP_0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP1,			BBCM_KEY_KP_1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP2,			BBCM_KEY_KP_2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP3,			BBCM_KEY_KP_3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP4,			BBCM_KEY_KP_4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP5,			BBCM_KEY_KP_5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP6,			BBCM_KEY_KP_6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP7,			BBCM_KEY_KP_7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP8,			BBCM_KEY_KP_8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP9,			BBCM_KEY_KP_9,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_NUMLOCK,		BBCM_KEY_KP_COMMA,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPPLUS,		BBCM_KEY_KP_PLUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPMINUS,		BBCM_KEY_KP_MINUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPSTAR,		BBCM_KEY_KP_STAR,

SCAN_CODE_ESCAPE,		SCAN_CODE_KPSLASH,		BBCM_KEY_KP_SLASH,
SCAN_CODE_ESCAPE,		SCAN_CODE_KPENTER,		BBCM_KEY_KP_ENTER,
SCAN_CODE_ESCAPE,		SCAN_CODE_INSERT,		BBCM_KEY_KP_HASH,
SCAN_CODE_ESCAPE,		SCAN_CODE_DELETE,		BBCM_KEY_KP_DEL,

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};


/*
  The shift key table, this has the same format as the above standard 
  key table, however when one of these keys is pressed, the output shift 
  key will also be pressed before the key, and released after the key.
	
  This allows as single PC key to translate to a SHIFT-KEY combination 
  on the output matrix. 
  
  A similar method could be used for other modifier keys.
*/

const uint8_t ScancodeShiftTableBBCMaster[] PROGMEM = {
// Prefix code			Scancode				Keycode
SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};

void ScancodeInit(matrix_t *ToInit)
{
	ToInit->ScancodeTable=(uint8_t *)ScancodeTableBBCMaster;
	ToInit->ScancodeShiftTable=(uint8_t *)ScancodeShiftTableBBCMaster;
	ToInit->matrix_shift=BBCM_KEY_SHIFT;
	ToInit->matrix_reset=RESET_KEY;
}
