/*
  PC Scan Code to Atom Column/Row translation table.

  Encoded as follows, 
  Each record consists of 3 bytes :-
 
  1) The prefix code, either SCAN_CODE_NO_PREFIX, or SCAN_CODE_ESCAPE
  2) The PC scan code to check for, from scancode.h
  3) The atom key it represents, from constant table above.

  This table should ONLY contain mappings for which there is a valid
  output key.

  Working out this table took far too long !!!!
*/

#include "scancode.h"

const uint8_t ScancodeTableAtom[] PROGMEM = {
// Prefix code			Scancode				Keycode
SCAN_CODE_NO_PREFIX,	SCAN_CODE_A,			ATOM_KEY_A,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_B,			ATOM_KEY_B,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_C,			ATOM_KEY_C,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_D,			ATOM_KEY_D,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_E,			ATOM_KEY_E,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_F,			ATOM_KEY_F,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_G,			ATOM_KEY_G,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_H,			ATOM_KEY_H,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_I,			ATOM_KEY_I,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_J,			ATOM_KEY_J,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_K,			ATOM_KEY_K,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_L,			ATOM_KEY_L,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_M,			ATOM_KEY_M,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_N,			ATOM_KEY_N,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_O,			ATOM_KEY_O,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_P,			ATOM_KEY_P,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Q,			ATOM_KEY_Q,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_R,			ATOM_KEY_R,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_S,			ATOM_KEY_S,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_T,			ATOM_KEY_T,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_U,			ATOM_KEY_U,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_V,			ATOM_KEY_V,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_W,			ATOM_KEY_W,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_X,			ATOM_KEY_X,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Y,			ATOM_KEY_Y,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_Z,			ATOM_KEY_Z,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_0,			ATOM_KEY_0,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_1,			ATOM_KEY_1,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_2,			ATOM_KEY_2,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_3,			ATOM_KEY_3,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_4,			ATOM_KEY_4,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_5,			ATOM_KEY_5,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_6,			ATOM_KEY_6,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_7,			ATOM_KEY_7,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_8,			ATOM_KEY_8,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_9,			ATOM_KEY_9,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SPACE,		ATOM_KEY_SPACE,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_POINT,		ATOM_KEY_POINT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_COMMA,		ATOM_KEY_COMMA,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SLASH,		ATOM_KEY_SLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_SEMICOLON,	ATOM_KEY_SEMICOLON,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSQBRACK,		ATOM_KEY_RBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSQBRACK,		ATOM_KEY_LBRACK,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_QUOTE,		ATOM_KEY_AT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_BSLASH,		ATOM_KEY_BSLASH,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_MINUS,		ATOM_KEY_MINUS,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_EQUAL,		ATOM_KEY_COLON,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_TILDE,		ATOM_KEY_CLARET,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_BACKSPACE,	ATOM_KEY_DELETE,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_LSHIFT,		ATOM_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_LALT,			ATOM_KEY_SHIFT,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_RSHIFT,		ATOM_KEY_SHIFT,
SCAN_CODE_ESCAPE,		SCAN_CODE_LGUI,			ATOM_KEY_SHIFT,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_LCTRL,		ATOM_KEY_CTRL,
SCAN_CODE_ESCAPE,		SCAN_CODE_RCTRL,		ATOM_KEY_CTRL,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ENTER,		ATOM_KEY_ENTER,
SCAN_CODE_ESCAPE,		SCAN_CODE_KPENTER,		ATOM_KEY_ENTER,

SCAN_CODE_ESCAPE,		SCAN_CODE_RALT,			ATOM_KEY_COPY,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_ESC,			ATOM_KEY_ESC,

SCAN_CODE_ESCAPE,		SCAN_CODE_UARROW,		ATOM_KEY_UD,
SCAN_CODE_ESCAPE,		SCAN_CODE_RARROW,		ATOM_KEY_LR,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_CAPSLOCK,		ATOM_KEY_LOCK,

SCAN_CODE_NO_PREFIX,	SCAN_CODE_KPPOINT,		ATOM_KEY_REPT,
SCAN_CODE_ESCAPE,		SCAN_CODE_KPPOINT,		ATOM_KEY_REPT,

SCAN_CODE_ESCAPE,		SCAN_CODE_PAUSE,		ATOM_KEY_BREAK,

// Keypad remaps for Bas
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP8,			ATOM_KEY_UD,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP6,			ATOM_KEY_LR,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP5,			ATOM_KEY_ENTER,

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};


/*
  The shift key table, this has the same format as the above standard 
  key table, however when one of these keys is pressed, the output shift 
  key will also be pressed before the key, and released after the key.
	
  This allows as single PC key to translate to a SHIFT-KEY combination 
  on the output matrix. 
  
  A similar method could be used for other modifier keys.
*/

const uint8_t ScancodeShiftTableAtom[] PROGMEM = {
// Prefix code			Scancode				Keycode

SCAN_CODE_ESCAPE,		SCAN_CODE_DARROW,		ATOM_KEY_UD,
SCAN_CODE_ESCAPE,		SCAN_CODE_LARROW,		ATOM_KEY_LR,

// Keypad remaps for Bas
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP2,			ATOM_KEY_UD,
SCAN_CODE_NO_PREFIX,	SCAN_CODE_KP4,			ATOM_KEY_LR,

SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE, 	SCAN_CODE_TERMINATE
};

void ScancodeInit(matrix_t *ToInit)
{
	ToInit->ScancodeTable=(uint8_t *)ScancodeTableAtom;
	ToInit->ScancodeShiftTable=(uint8_t *)ScancodeShiftTableAtom;
	ToInit->matrix_shift=ATOM_KEY_SHIFT;
	ToInit->matrix_reset=RESET_KEY;
}
